name: Firmware

# build for each push, pull request, also publish to new releases
on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile firmware
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          libraries: |
            - name: Servo
            - source-url: https://github.com/johnrickman/LiquidCrystal_I2C.git
            - source-url: https://github.com/bogde/HX711.git
          sketch-paths: "- arduino_code"
          enable-deltas-report: true
          enable-warnings-report: true
          cli-compile-flags: |
            - --export-binaries
      - name: Upload binary
        uses: actions/upload-artifact@v4.0.0
        with:
          name: openautolab.hex
          path: arduino_code/**/*.hex
      - name: Upload release files
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: arduino_code/**/*.hex
          asset_name: openautolab.hex
          asset_content_type: binary/octet-stream
