# compile.yml
#
# Copyright (c) 2023 - 2024 Kauzerei <openautolab@kauzerei.de>
# Copyright (c) 2023 - 2024 Thomas Buck <thomas@xythobuz.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

name: Firmware

# build for each push and pull request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout repo submodules
        run: git submodule update --init

      - name: Compile firmware
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          libraries: |
            - name: Servo
            - source-url: https://github.com/johnrickman/LiquidCrystal_I2C.git
            - source-url: https://github.com/bogde/HX711.git
          sketch-paths: "- arduino_code"
          enable-deltas-report: true
          enable-warnings-report: true
          cli-compile-flags: |
            - --export-binaries

      - name: Upload binary
        uses: actions/upload-artifact@v4.0.0
        with:
          name: openautolab.hex
          path: arduino_code/**/*.hex

      - name: Archive release files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd arduino_code/openautolab/build/arduino.avr.nano
          zip openautolab-hex *.hex

      - name: Upload release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: arduino_code/openautolab/build/arduino.avr.nano/openautolab-hex.zip
