name: Compile
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          libraries: |
            - name: Servo
            - source-url: https://github.com/johnrickman/LiquidCrystal_I2C.git
            - source-url: https://github.com/bogde/HX711.git
          sketch-paths: "- arduino_code/openautolab"
