name: Firmware
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile firmware
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano"
          libraries: |
            - name: Servo
            - source-url: https://github.com/johnrickman/LiquidCrystal_I2C.git
            - source-url: https://github.com/bogde/HX711.git
          sketch-paths: "- arduino_code"
          cli-compile-flags: "--export-binaries"
      - name: Upload binary
        uses: actions/upload-artifact@v4.0.0
        with:
          name: openautolab.hex
          path: ${{github.workspace}}/openautolab/*.hex
