name: STLs

# build for each push and pull request
on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install -y openscad zip
      - name: Render STLs
        run: |
          ./parts/generate_stls.sh
      - name: Upload part files
        uses: actions/upload-artifact@v4.0.0
        with:
          name: openautolab-stl
          path: parts/stl
      - name: Archive release files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd parts
          zip -r openautolab-stl stl
      - name: Upload release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: openautolab-stl.zip
